version: "2"
services:
  qweree-db:
    container_name: qweree-db
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - qweree-db:/data/db

  qweree-auth:
    container_name: qweree-auth
    depends_on:
      - qweree-db
    build:
      dockerfile: ./docker/Qweree.Authentication.WebApi.Dockerfile
      context: .
    restart: always
    environment:
      Qweree__MongoConnectionString: "mongodb://qweree-db:27017"
      Qweree__HealthCheckConnectionString: "mongodb://qweree-db:27017"
      Qwereee__PathBase: "/auth"

  qweree-cdn:
    container_name: qweree-cdn
    depends_on:
      - qweree-db
    build:
      dockerfile: ./docker/Qweree.Cdn.WebApi.Dockerfile
      context: .
    restart: always
    volumes:
      - qweree-cdn:/qweree-storage
    environment:
      Qweree__MongoConnectionString: "mongodb://qweree-db:27017"
      Qweree__HealthCheckConnectionString: "mongodb://qweree-db:27017"
      Qweree__AuthUri: "http://qweree-auth"
      Qweree__SwaggerOpenId: "https://localhost/auth/api/.well-known/opeid-configuration"
      Qweree__FileSystemRoot: "/qweree-storage"
      Qweree__FileSystemTemp: "/qweree-temp"
      Qweree__PathBase: "/cdn"

  qweree-picc:
    container_name: qweree-picc
    depends_on:
      - qweree-db
    build:
      dockerfile: ./docker/Qweree.PiccStash.WebApi.Dockerfile
      context: .
    restart: always
    environment:
      Qweree__MongoConnectionString: "mongodb://qweree-db:27017"
      Qweree__HealthCheckConnectionString: "mongodb://qweree-db:27017"
      Qweree__AuthUri: "http://qweree-auth"
      Qweree__SwaggerOpenId: "https://localhost/auth/api/.well-known/opeid-configuration"
      Qweree__PathBase: "/picc"
      Qweree__CdnUri: "http://qweree-cdn/api/v1/storage/"

  qweree-webapp:
    container_name: qweree-webapp
    build:
      dockerfile: ./docker/Qweree.WebApplication.Dockerfile
      context: .
    restart: always
    environment:
       ASPNETCORE_URLS: http://localhost:80

  qweree-gateway:
    container_name: qweree-gateway
    build:
      dockerfile: ./docker/Qweree.Gateway.WebApi.Dockerfile
      context: .
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/.aspnet/https:/https:ro
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      Urls: "http://*80;https://*:443"
      Qweree__AuthUri: "http://qweree-auth"
      Qweree__CdnUri: "http://qweree-cdn/api/v1/storage/"
      ReverseProxy__Clusters__qweree.authentication__Destinations__default__Address: "http://qweree-auth"
      ReverseProxy__Clusters__qweree.cdn__Destinations__default__Address: "http://qweree-cdn"
      ReverseProxy__Clusters__qweree.picc__Destinations__default__Address: "http://qweree-picc"
      ReverseProxy__Clusters__qweree.webapp__Destinations__default__Address: "http://qweree-webapp"

volumes:
  qweree-db:
  qweree-cdn:
