version: "2"
services:
  qweree-db:
    container_name: qweree-db
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - qweree-db:/data/db

  qweree-auth:
    container_name: qweree-auth
    depends_on:
      - qweree-db
    build:
      dockerfile: ./docker/Qweree.Authentication.WebApi/.Dockerfile
      context: .
    restart: always
    ports:
      - "10001:80"
    environment:
      Database__ConnectionString: "mongodb://qweree-db:27017"
      HealthChecks__Database__ConnectionString: "mongodb://qweree-db:27017"

  qweree-cdn:
    container_name: qweree-cdn
    depends_on:
      - qweree-db
    build:
      dockerfile: ./docker/Qweree.Cdn.WebApi/.Dockerfile
      context: .
    restart: always
    ports:
      - "10002:80"
    volumes:
      - qweree-cdn:/storage
    environment:
      Database__ConnectionString: "mongodb://qweree-db:27017"
      HealthChecks__Database__ConnectionString: "mongodb://qweree-db:27017"
      Authentication__TokenUri: "http://qweree-auth:10001/api/oauth2/auth"
      Storage__FileSystemRoot: "/storage"

  qweree-qwill:
    container_name: qweree-qwill
    depends_on:
      - qweree-db
    build:
      dockerfile: ./docker/Qweree.Qwill.WebApi/.Dockerfile
      context: .
    restart: always
    ports:
      - "10003:80"
    environment:
      Database__ConnectionString: "mongodb://qweree-db:27017"
      HealthChecks__Database__ConnectionString: "mongodb://qweree-db:27017"
      Authentication__TokenUri: "http://qweree-auth:10001/api/oauth2/auth"

  qweree-qadmin:
    container_name: qweree-qadmin
    build: 
      dockerfile: ./docker/Qweree.QAdmin.WebApplication/.Dockerfile
      context: .
    restart: always
    ports: 
      - "11001:80"

volumes:
  qweree-db:
  qweree-cdn:
