version: "2"
services:
  qweree-proxy:
    container_name: qweree-proxy
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src/Qweree.ReverseProxy/config/nginx.conf:/etc/nginx/nginx.conf

  qweree-db:
    container_name: qweree-db
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - qweree-db:/data/db

  qweree-auth:
    container_name: qweree-auth
    depends_on:
      - qweree-db
    build:
      dockerfile: ./docker/Qweree.Authentication.WebApi.Dockerfile
      context: .
    restart: always
    environment:
      Database__ConnectionString: "mongodb://qweree-db:27017"
      HealthChecks__Database__ConnectionString: "mongodb://qweree-db:27017"
      Routing__PathBase: "/auth"

  qweree-cdn:
    container_name: qweree-cdn
    depends_on:
      - qweree-db
    build:
      dockerfile: ./docker/Qweree.Cdn.WebApi.Dockerfile
      context: .
    restart: always
    volumes:
      - qweree-cdn:/storage
    environment:
      Database__ConnectionString: "mongodb://qweree-db:27017"
      HealthChecks__Database__ConnectionString: "mongodb://qweree-db:27017"
      Authentication__TokenUri: "http://localhost/auth/api/oauth2/auth"
      Swagger__TokenUri: "http://localhost/auth/api/oauth2/auth"
      Storage__FileSystemRoot: "/storage"
      Routing__PathBase: "/cdn"

  qweree-picc:
    container_name: qweree-picc
    depends_on:
      - qweree-db
    build:
      dockerfile: ./docker/Qweree.PiccStash.WebApi.Dockerfile
      context: .
    restart: always
    environment:
      Database__ConnectionString: "mongodb://qweree-db:27017"
      HealthChecks__Database__ConnectionString: "mongodb://qweree-db:27017"
      Authentication__TokenUri: "http://qweree-auth/api/oauth2/auth"
      Swagger__TokenUri: "http://localhost/auth/api/oauth2/auth"
      Storage__CdnUri: "http://qweree-cdn/api/v1/storage/"
      Routing__PathBase: "/picc"
volumes:
  qweree-db:
  qweree-cdn:
