version: "2"
services:
  qweree-db:
    container_name: qweree-db
    image: mongo:latest
    restart: always
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - qweree-db:/data/db

  qweree-auth:
    container_name: qweree-auth
    depends_on:
      - qweree-db
    build:
      dockerfile: ./docker/Qweree.Authentication.WebApi/.Dockerfile
      context: ./../../
    restart: always
    environment:
      Database__ConnectionString: "mongodb://qweree-db:27017"
      HealthChecks__Database__ConnectionString: "mongodb://qweree-db:27017"

  qweree-cdn:
    container_name: qweree-cdn
    depends_on:
      - qweree-db
    build:
      dockerfile: ./docker/Qweree.Cdn.WebApi/.Dockerfile
      context: ./../../
    restart: always
    volumes:
      - qweree-cdn:/storage
    environment:
      Database__ConnectionString: "mongodb://qweree-db:27017"
      HealthChecks__Database__ConnectionString: "mongodb://qweree-db:27017"
      Authentication__TokenUri: "http://qweree-auth:8080/api/oauth2/auth"
      Storage__FileSystemRoot: "/storage"

  qweree-qadmin:
    container_name: qweree-qadmin
    build:
      dockerfile: ./docker/Qweree.QAdmin.WebApplication/.Dockerfile
      context: ./../../
    restart: always

  qweree-proxy:
    container_name: qweree-proxy
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src/Qweree.ReverseProxy/config/nginx.conf:/etc/nginx/


volumes:
  qweree-db:
  qweree-cdn:
