name: .NET

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Setup docker
        run: docker-compose up -d qweree-auth qweree-cdn
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

  code_inspection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 3
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Add dotnet tool
        run: dotnet tool restore
      - name: Analyse
        run: dotnet jb inspectcode Qweree.sln -o=output.xml
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: output.xml
          path: output.xml